name: Eleventy Build


on:
  push:
    branches: ["main"]
      
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2


        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: '22.5.1'


        - run: npm install


        - run: npm run build


        - name: Deploy
          id: deployment
          uses: actions/deploy-pages@v2
